top = {   '0': 'Management Occupations',
    '1': 'Business, Finance and Administration Occupations',
    '2': 'Natural and Applied Sciences and Related Occupations',
    '3': 'Health Occupations',
    '4': 'Occupations in Social Science, Education, Government Service and Religion',
    '5': 'Occupations in Art, Culture, Recreation and Sport',
    '6': 'Sales and Service Occupations',
    '7': 'Trades, Transport and Equipment Operators and Related Occupations',
    '8': 'Occupations Unique to Primary Industry',
    '9': 'Occupations Unique to Processing, Manufacturing and Utilities'}

major = {   '00': 'Senior Management Occupations',
    '01': 'Middle and Other Management Occupations',
    '02': 'Middle and Other Management Occupations',
    '03': 'Middle and Other Management Occupations',
    '04': 'Middle and Other Management Occupations',
    '05': 'Middle and Other Management Occupations',
    '06': 'Middle and Other Management Occupations',
    '07': 'Middle and Other Management Occupations',
    '08': 'Middle and Other Management Occupations',
    '09': 'Middle and Other Management Occupations',
    '11': 'Professional Occupations in Business and Finance',
    '12': 'Skilled Administrative and Business Occupations',
    '14': 'Clerical Occupations',
    '21': 'Professional Occupations in Natural and Applied Sciences',
    '22': 'Technical Occupations Related to Natural and Applied Sciences',
    '31': 'Professional Occupations in Health',
    '32': 'Technical and Skilled Occupations in Health',
    '34': 'Assisting Occupations in Support of Health Services',
    '41': 'Professional Occupations in Social Science, Education, Government Services and Religion',
    '42': 'Paraprofessional Occupations in Law, Social Services, Education and Religion',
    '51': 'Professional Occupations in Art and Culture',
    '52': 'Technical and Skilled Occupations in Art, Culture, Recreation and Sport',
    '62': 'Skilled Sales and Service Occupations',
    '64': 'Intermediate Sales and Service Occupations',
    '66': 'Elemental Sales and Service Occupations',
    '72': 'Trades and Skilled Transport and Equipment Operators',
    '73': 'Trades and Skilled Transport and Equipment Operators',
    '74': 'Intermediate Occupations in Transport, Equipment Operation, Installation and Maintenance',
    '76': 'Trades Helpers, Construction Labourers and Related Occupations',
    '82': 'Skilled Occupations in Primary Industry',
    '84': 'Intermediate Occupations in Primary Industry',
    '86': 'Labourers in Primary Industry',
    '92': 'Processing, Manufacturing and Utilities Supervisors and Skilled Operators',
    '94': 'Processing and Manufacturing Machine Operators and Assemblers',
    '95': 'Processing and Manufacturing Machine Operators and Assemblers',
    '96': 'Labourers in Processing, Manufacturing and Utilities'}

minor = {   '001': 'Legislators and Senior Management',
    '011': 'Administrative Services Managers',
    '012': 'Managers in Financial and Business Services',
    '013': 'Managers in Communication (Except Broadcasting)',
    '021': 'Managers in Engineering, Architecture, Science and Information Systems',
    '031': 'Managers in Health, Education, Social and Community Services',
    '041': 'Managers in Public Administration',
    '051': 'Managers in Art, Culture, Recreation and Sport',
    '061': 'Sales, Marketing and Advertising Managers',
    '062': 'Managers in Retail Trade',
    '063': 'Managers in Food Service and Accommodation',
    '064': 'Managers in Protective Service',
    '065': 'Managers in Other Services',
    '071': 'Managers in Construction and Transportation',
    '072': 'Facility Operation and Maintenance Managers',
    '081': 'Managers in Primary Production (Except Agriculture)',
    '091': 'Managers in Manufacturing and Utilities',
    '111': 'Auditors, Accountants and Investment Professionals',
    '112': 'Human Resources and Business Service Professionals',
    '121': 'Clerical Supervisors',
    '122': 'Administrative and Regulatory Occupations',
    '123': 'Finance and Insurance Administrative Occupations',
    '124': 'Secretaries, Recorders and Transcriptionists',
    '141': 'Clerical Occupations, General Office Skills',
    '142': 'Office Equipment Operators',
    '143': 'Finance and Insurance Clerks',
    '144': 'Administrative Support Clerks',
    '145': 'Library, Correspondence and Related Information Clerks',
    '146': 'Mail and Message Distribution Occupations',
    '147': 'Recording, Scheduling and Distributing Occupations',
    '211': 'Physical Science Professionals',
    '212': 'Life Science Professionals',
    '213': 'Civil, Mechanical, Electrical and Chemical Engineers',
    '214': 'Other Engineers',
    '215': 'Architects, Urban Planners and Land Surveyors',
    '216': 'Mathematicians, Statisticians and Actuaries',
    '217': 'Computer and Information Systems Professionals',
    '221': 'Technical Occupations in Physical Sciences',
    '222': 'Technical Occupations in Life Sciences',
    '223': 'Technical Occupations in Civil, Mechanical and Industrial Engineering',
    '224': 'Technical Occupations in Electronics and Electrical Engineering',
    '225': 'Technical Occupations in Architecture, Drafting, Surveying and Mapping',
    '226': 'Other Technical Inspectors and Regulatory Officers',
    '227': 'Transportation Officers and Controllers',
    '228': 'Technical Occupations in Computer and Information Systems',
    '311': 'Physicians, Dentists and Veterinarians',
    '312': 'Optometrists, Chiropractors and Other Health Diagnosing and Treating Professionals',
    '313': 'Pharmacists, Dietitians and Nutritionists',
    '314': 'Therapy and Assessment Professionals',
    '315': 'Nurse Supervisors and Registered Nurses',
    '321': 'Medical Technologists and Technicians (Except Dental Health)',
    '322': 'Technical Occupations in Dental Health Care',
    '323': 'Other Technical Occupations in Health Care (Except Dental)',
    '341': 'Assisting Occupations in Support of Health Services',
    '411': 'Judges, Lawyers and Quebec Notaries',
    '412': 'University Professors and Assistants',
    '413': 'College and Other Vocational Instructors',
    '414': 'Secondary and Elementary School Teachers and Educational Counsellors',
    '415': 'Psychologists, Social Workers, Counsellors, Clergy and Probation Officers',
    '416': 'Policy and Program Officers, Researchers and Consultants',
    '421': 'Paralegals, Social Services Workers and Occupations in Education and Religion, n.e.c.',
    '511': 'Librarians, Archivists, Conservators and Curators',
    '512': 'Writing, Translating and Public Relations Professionals',
    '513': 'Creative and Performing Artists',
    '521': 'Technical Occupations in Libraries, Archives, Museums and Art Galleries',
    '522': 'Photographers, Graphic Arts Technicians and Technical\n and Co-ordinating Occupations in Motion Pictures, Broadcasting and the \nPerforming Arts',
    '523': 'Announcers and Other Performers',
    '524': 'Creative Designers and Craftspersons',
    '525': 'Athletes, Coaches, Referees and Related Occupations',
    '621': 'Sales and Service Supervisors',
    '622': 'Technical Sales Specialists, Wholesale Trade',
    '623': 'Insurance and Real Estate Sales Occupations and Buyers',
    '624': 'Chefs and Cooks',
    '625': 'Butchers and Bakers',
    '626': 'Police Officers and Firefighters',
    '627': 'Technical Occupations in Personal Service',
    '641': 'Sales Representatives, Wholesale Trade',
    '642': 'Retail Salespersons and Sales Clerks',
    '643': 'Occupations in Travel and Accommodation',
    '644': 'Tour and Recreational Guides and Casino Occupations',
    '645': 'Occupations in Food and Beverage Service',
    '646': 'Other Occupations in Protective Service',
    '647': 'Childcare and Home Support Workers',
    '648': 'Other Occupations in Personal Service',
    '661': 'Cashiers',
    '662': 'Other Sales and Related Occupations',
    '664': 'Food Counter Attendants, Kitchen Helpers and Related Occupations',
    '665': 'Security Guards and Related Occupations',
    '666': 'Cleaners',
    '667': 'Other Occupations in Travel, Accommodation, Amusement and Recreation',
    '668': 'Other Elemental Service Occupations',
    '721': 'Contractors and Supervisors, Trades and Related Workers',
    '722': 'Supervisors, Railway and Motor Transportation Occupations',
    '723': 'Machinists and Related Occupations',
    '724': 'Electrical Trades and Telecommunication Occupations',
    '725': 'Plumbers, Pipefitters and Gas Fitters',
    '726': 'Metal Forming, Shaping and Erecting Trades',
    '727': 'Carpenters and Cabinetmakers',
    '728': 'Masonry and Plastering Trades',
    '729': 'Other Construction Trades',
    '731': 'Machinery and Transportation Equipment Mechanics (Except Motor Vehicle)',
    '732': 'Automotive Service Technicians',
    '733': 'Other Mechanics',
    '734': 'Upholsterers, Tailors, Shoe Repairers, Jewellers and Related Occupations',
    '735': 'Stationary Engineers and Power Station and System Operators',
    '736': 'Train Crew Operating Occupations',
    '737': 'Crane Operators, Drillers and Blasters',
    '738': 'Printing Press Operators, Commercial Divers and Other Trades and Related Occupations, n.e.c.',
    '741': 'Motor Vehicle and Transit Drivers',
    '742': 'Heavy Equipment Operators',
    '743': 'Other Transport Equipment Operators and Related Workers',
    '744': 'Other Installers, Repairers and Servicers',
    '745': 'Longshore Workers and Material Handlers',
    '761': 'Trades Helpers and Labourers',
    '762': 'Public Works and Other Labourers, n.e.c.',
    '821': 'Supervisors, Logging and Forestry',
    '822': 'Supervisors, Mining, Oil and Gas',
    '823': 'Underground Miners, Oil and Gas Drillers and Related Workers',
    '824': 'Logging Machinery Operators',
    '825': 'Contractors, Operators and Supervisors in Agriculture, Horticulture and Aquaculture',
    '826': 'Fishing Vessel Masters and Skippers and Fishermen/women',
    '841': 'Mine Service Workers and Operators in Oil and Gas Drilling',
    '842': 'Logging and Forestry Workers',
    '843': 'Agriculture and Horticulture Workers',
    '844': 'Other Fishing and Trapping Occupations',
    '861': 'Primary Production Labourers',
    '921': 'Supervisors, Processing Occupations',
    '922': 'Supervisors, Assembly and Fabrication',
    '923': 'Central Control and Process Operators in Manufacturing and Processing',
    '941': 'Machine Operators and Related Workers in Metal and Mineral Products Processing',
    '942': 'Machine Operators and Related Workers in Chemical, Plastic and Rubber Processing',
    '943': 'Machine Operators and Related Workers in Pulp and Paper Production and Wood Processing',
    '944': 'Machine Operators and Related Workers in Textile Processing',
    '945': 'Machine Operators and Related Workers in Fabric, Fur and Leather Products Manufacturing',
    '946': 'Machine Operators and Related Workers in Food, Beverage and Tobacco Processing',
    '947': 'Printing Machine Operators and Related Occupations',
    '948': 'Mechanical, Electrical and Electronics Assemblers',
    '949': 'Other Assembly and Related Occupations',
    '951': 'Machining, Metalworking, Woodworking and Related Machine Operators',
    '961': 'Labourers in Processing, Manufacturing and Utilities'}

individual = {   '0011': 'Legislators',
    '0012': 'Senior Government Managers and Officials',
    '0013': 'Senior Managers - Financial, Communications and Other Business Services',
    '0014': 'Senior Managers - Health, Education, Social and Community Services and Membership Organizations',
    '0015': 'Senior Managers - Trade, Broadcasting and Other Services, n.e.c.',
    '0016': 'Senior Managers - Goods Production, Utilities, Transportation and Construction',
    '0111': 'Financial Managers',
    '0112': 'Human Resources Managers',
    '0113': 'Purchasing Managers',
    '0114': 'Other Administrative Services Managers',
    '0121': 'Insurance, Real Estate and Financial Brokerage Managers',
    '0122': 'Banking, Credit and Other Investment Managers',
    '0123': 'Other Business Services Managers',
    '0131': 'Telecommunication Carriers Managers',
    '0132': 'Postal and Courier Services Managers',
    '0211': 'Engineering Managers',
    '0212': 'Architecture and Science Managers',
    '0213': 'Computer and Information Systems Managers',
    '0311': 'Managers in Health Care',
    '0312': 'Administrators - Post-Secondary Education and Vocational Training',
    '0313': 'School Principals and Administrators of Elementary and Secondary Education',
    '0314': 'Managers in Social, Community and Correctional Services',
    '0411': 'Government Managers - Health and Social Policy Development and Program Administration',
    '0412': 'Government Managers - Economic Analysis, Policy Development and Program Administration',
    '0413': 'Government Managers - Education Policy Development and Program Administration',
    '0414': 'Other Managers in Public Administration',
    '0511': 'Library, Archive, Museum and Art Gallery Managers',
    '0512': 'Managers - Publishing, Motion Pictures, Broadcasting and Performing Arts',
    '0513': 'Recreation, Sports and Fitness Program and Service Directors',
    '0611': 'Sales, Marketing and Advertising Managers',
    '0621': 'Retail Trade Managers',
    '0631': 'Restaurant and Food Service Managers',
    '0632': 'Accommodation Service Managers',
    '0641': 'Commissioned Police Officers',
    '0642': 'Fire Chiefs and Senior Firefighting Officers',
    '0643': 'Commissioned Officers, Armed Forces',
    '0651': 'Other Services Managers',
    '0711': 'Construction Managers',
    '0712': 'Residential Home Builders and Renovators',
    '0713': 'Transportation Managers',
    '0721': 'Facility Operation and Maintenance Managers',
    '0811': 'Primary Production Managers (Except Agriculture)',
    '0911': 'Manufacturing Managers',
    '0912': 'Utilities Managers',
    '1111': 'Financial Auditors and Accountants',
    '1112': 'Financial and Investment Analysts',
    '1113': 'Securities Agents, Investment Dealers and Brokers',
    '1114': 'Other Financial Officers',
    '1121': 'Specialists in Human Resources',
    '1122': 'Professional Occupations in Business Services to Management',
    '1211': 'Supervisors, General Office and Administrative Support Clerks',
    '1212': 'Supervisors, Finance and Insurance Clerks',
    '1213': 'Supervisors, Library, Correspondence and Related Information Clerks',
    '1214': 'Supervisors, Mail and Message Distribution Occupations',
    '1215': 'Supervisors, Recording, Distributing and Scheduling Occupations',
    '1221': 'Administrative Officers',
    '1222': 'Executive Assistants',
    '1223': 'Personnel and Recruitment Officers',
    '1224': 'Property Administrators',
    '1225': 'Purchasing Agents and Officers',
    '1226': 'Conference and Event Planners',
    '1227': 'Court Officers and Justices of the Peace',
    '1228': 'Immigration, Employment Insurance and Revenue Officers',
    '1231': 'Bookkeepers',
    '1232': 'Loan Officers',
    '1233': 'Insurance Adjusters and Claims Examiners',
    '1234': 'Insurance Underwriters',
    '1235': 'Assessors, Valuators and Appraisers',
    '1236': 'Customs, Ship and Other Brokers',
    '1241': 'Secretaries (Except Legal and Medical)',
    '1242': 'Legal Secretaries',
    '1243': 'Medical Secretaries',
    '1244': 'Court Recorders and Medical Transcriptionists',
    '1411': 'General Office Clerks',
    '1413': 'Records Management and Filing Clerks',
    '1414': 'Receptionists and Switchboard Operators',
    '1422': 'Data Entry Clerks',
    '1423': 'Desktop Publishing Operators and Related Occupations',
    '1424': 'Telephone Operators',
    '1431': 'Accounting and Related Clerks',
    '1432': 'Payroll Clerks',
    '1433': 'Customer Service Representatives - Financial Services',
    '1434': 'Banking, Insurance and Other Financial Clerks',
    '1435': 'Collectors',
    '1441': 'Administrative Clerks',
    '1442': 'Personnel Clerks',
    '1443': 'Court Clerks',
    '1451': 'Library Clerks',
    '1452': 'Correspondence, Publication and Related Clerks',
    '1453': 'Customer Service, Information and Related Clerks',
    '1454': 'Survey Interviewers and Statistical Clerks',
    '1461': 'Mail, Postal and Related Clerks',
    '1462': 'Letter Carriers',
    '1463': 'Couriers, Messengers and Door-to-Door Distributors',
    '1471': 'Shippers and Receivers',
    '1472': 'Storekeepers and Parts Clerks',
    '1473': 'Production Clerks',
    '1474': 'Purchasing and Inventory Clerks',
    '1475': 'Dispatchers and Radio Operators',
    '1476': 'Transportation Route and Crew Schedulers',
    '2111': 'Physicists and Astronomers',
    '2112': 'Chemists',
    '2113': 'Geologists, Geochemists and Geophysicists',
    '2114': 'Meteorologists',
    '2115': 'Other Professional Occupations in Physical Sciences',
    '2121': 'Biologists and Related Scientists',
    '2122': 'Forestry Professionals',
    '2123': 'Agricultural Representatives, Consultants and Specialists',
    '2131': 'Civil Engineers',
    '2132': 'Mechanical Engineers',
    '2133': 'Electrical and Electronics Engineers',
    '2134': 'Chemical Engineers',
    '2141': 'Industrial and Manufacturing Engineers',
    '2142': 'Metallurgical and Materials Engineers',
    '2143': 'Mining Engineers',
    '2144': 'Geological Engineers',
    '2145': 'Petroleum Engineers',
    '2146': 'Aerospace Engineers',
    '2147': 'Computer Engineers (Except Software Engineers and Designers)',
    '2148': 'Other Professional Engineers, n.e.c.',
    '2151': 'Architects',
    '2152': 'Landscape Architects',
    '2153': 'Urban and Land Use Planners',
    '2154': 'Land Surveyors',
    '2161': 'Mathematicians, Statisticians and Actuaries',
    '2171': 'Information Systems Analysts and Consultants',
    '2172': 'Database Analysts and Data Administrators',
    '2173': 'Software Engineers and Designers',
    '2174': 'Computer Programmers and Interactive Media Developers',
    '2175': 'Web Designers and Developers',
    '2211': 'Chemical Technologists and Technicians',
    '2212': 'Geological and Mineral Technologists and Technicians',
    '2213': 'Meteorological Technicians',
    '2221': 'Biological Technologists and Technicians',
    '2222': 'Agricultural and Fish Products Inspectors',
    '2223': 'Forestry Technologists and Technicians',
    '2224': 'Conservation and Fishery Officers',
    '2225': 'Landscape and Horticulture Technicians and Specialists',
    '2231': 'Civil Engineering Technologists and Technicians',
    '2232': 'Mechanical Engineering Technologists and Technicians',
    '2233': 'Industrial Engineering and Manufacturing Technologists and Technicians',
    '2234': 'Construction Estimators',
    '2241': 'Electrical and Electronics Engineering Technologists and Technicians',
    '2242': 'Electronic Service Technicians (Household and Business Equipment)',
    '2243': 'Industrial Instrument Technicians and Mechanics',
    '2244': 'Aircraft Instrument, Electrical and Avionics Mechanics, Technicians and Inspectors',
    '2251': 'Architectural Technologists and Technicians',
    '2252': 'Industrial Designers',
    '2253': 'Drafting Technologists and Technicians',
    '2254': 'Land Survey Technologists and Technicians',
    '2255': 'Mapping and Related Technologists and Technicians',
    '2261': 'Non-Destructive Testers and Inspectors',
    '2262': 'Engineering Inspectors and Regulatory Officers',
    '2263': 'Inspectors in Public and Environmental Health and Occupational Health and Safety',
    '2264': 'Construction Inspectors',
    '2271': 'Air Pilots, Flight Engineers and Flying Instructors',
    '2272': 'Air Traffic Control and Related Occupations',
    '2273': 'Deck Officers, Water Transport',
    '2274': 'Engineer Officers, Water Transport',
    '2275': 'Railway Traffic Controllers and Marine Traffic Regulators',
    '2281': 'Computer Network Technicians',
    '2282': 'User Support Technicians',
    '2283': 'Systems Testing Technicians',
    '3111': 'Specialist Physicians',
    '3112': 'General Practitioners and Family Physicians',
    '3113': 'Dentists',
    '3114': 'Veterinarians',
    '3121': 'Optometrists',
    '3122': 'Chiropractors',
    '3123': 'Other Professional Occupations in Health Diagnosing and Treating',
    '3131': 'Pharmacists',
    '3132': 'Dietitians and Nutritionists',
    '3141': 'Audiologists and Speech-Language Pathologists',
    '3142': 'Physiotherapists',
    '3143': 'Occupational Therapists',
    '3144': 'Other Professional Occupations in Therapy and Assessment',
    '3151': 'Head Nurses and Supervisors',
    '3152': 'Registered Nurses',
    '3211': "Medical Laboratory Technologists and Pathologists' Assistants",
    '3212': 'Medical Laboratory Technicians',
    '3213': 'Veterinary and Animal Health Technologists and Technicians',
    '3214': 'Respiratory Therapists, Clinical Perfusionists and Cardiopulmonary Technologists',
    '3215': 'Medical Radiation Technologists',
    '3216': 'Medical Sonographers',
    '3217': 'Cardiology Technologists',
    '3218': 'Electroencephalographic and Other Diagnostic Technologists, n.e.c.',
    '3219': 'Other Medical Technologists and Technicians (Except Dental Health)',
    '3221': 'Denturists',
    '3222': 'Dental Hygienists and Dental Therapists',
    '3223': 'Dental Technologists, Technicians and Laboratory Bench Workers',
    '3231': 'Opticians',
    '3232': 'Midwives and Practitioners of Natural Healing',
    '3233': 'Licensed Practical Nurses',
    '3234': 'Ambulance Attendants and Other Paramedical Occupations',
    '3235': 'Other Technical Occupations in Therapy and Assessment',
    '3411': 'Dental Assistants',
    '3413': 'Nurse Aides, Orderlies and Patient Service Associates',
    '3414': 'Other Assisting Occupations in Support of Health Services',
    '4111': 'Judges',
    '4112': 'Lawyers and Quebec Notaries',
    '4121': 'University Professors',
    '4122': 'Post-Secondary Teaching and Research Assistants',
    '4131': 'College and Other Vocational Instructors',
    '4141': 'Secondary School Teachers',
    '4142': 'Elementary School and Kindergarten Teachers',
    '4143': 'Educational Counsellors',
    '4151': 'Psychologists',
    '4152': 'Social Workers',
    '4153': 'Family, Marriage and Other Related Counsellors',
    '4154': 'Ministers of Religion',
    '4155': 'Probation and Parole Officers and Related Occupations',
    '4161': 'Natural and Applied Science Policy Researchers, Consultants and Program Officers',
    '4162': 'Economists and Economic Policy Researchers and Analysts',
    '4163': 'Business Development Officers and Marketing Researchers and Consultants',
    '4164': 'Social Policy Researchers, Consultants and Program Officers',
    '4165': 'Health Policy Researchers, Consultants and Program Officers',
    '4166': 'Education Policy Researchers, Consultants and Program Officers',
    '4167': 'Recreation, Sports and Fitness Program Supervisors and Consultants',
    '4168': 'Program Officers Unique to Government',
    '4169': 'Other Professional Occupations in Social Science, n.e.c.',
    '4211': 'Paralegal and Related Occupations',
    '4212': 'Community and Social Service Workers',
    '4213': 'Employment Counsellors',
    '4214': 'Early Childhood Educators and Assistants',
    '4215': 'Instructors and Teachers of Persons with Disabilities',
    '4216': 'Other Instructors',
    '4217': 'Other Religious Occupations',
    '5111': 'Librarians',
    '5112': 'Conservators and Curators',
    '5113': 'Archivists',
    '5121': 'Authors and Writers',
    '5122': 'Editors',
    '5123': 'Journalists',
    '5124': 'Professional Occupations in Public Relations and Communications',
    '5125': 'Translators, Terminologists and Interpreters',
    '5131': 'Producers, Directors, Choreographers and Related Occupations',
    '5132': 'Conductors, Composers and Arrangers',
    '5133': 'Musicians and Singers',
    '5134': 'Dancers',
    '5135': 'Actors and Comedians',
    '5136': 'Painters, Sculptors and Other Visual Artists',
    '5211': 'Library and Archive Technicians and Assistants',
    '5212': 'Technical Occupations Related to Museums and Art Galleries',
    '5221': 'Photographers',
    '5222': 'Film and Video Camera Operators',
    '5223': 'Graphic Arts Technicians',
    '5224': 'Broadcast Technicians',
    '5225': 'Audio and Video Recording Technicians',
    '5226': 'Other Technical and Co-ordinating Occupations in Motion Pictures, Broadcasting and the Performing Arts',
    '5227': 'Support Occupations in Motion Pictures, Broadcasting and the Performing Arts',
    '5231': 'Announcers and Other Broadcasters',
    '5232': 'Other Performers',
    '5241': 'Graphic Designers and Illustrators',
    '5242': 'Interior Designers',
    '5243': 'Theatre, Fashion, Exhibit and Other Creative Designers',
    '5244': 'Artisans and Craftspersons',
    '5245': 'Patternmakers - Textile, Leather and Fur Products',
    '5251': 'Athletes',
    '5252': 'Coaches',
    '5253': 'Sports Officials and Referees',
    '5254': 'Program Leaders and Instructors in Recreation, Sport and Fitness',
    '6211': 'Retail Trade Supervisors',
    '6212': 'Food Service Supervisors',
    '6213': 'Executive Housekeepers',
    '6214': 'Dry Cleaning and Laundry Supervisors',
    '6215': 'Cleaning Supervisors',
    '6216': 'Other Service Supervisors',
    '6221': 'Technical Sales Specialists - Wholesale Trade',
    '6231': 'Insurance Agents and Brokers',
    '6232': 'Real Estate Agents and Salespersons',
    '6233': 'Retail and Wholesale Buyers',
    '6234': 'Grain Elevator Operators',
    '6241': 'Chefs',
    '6242': 'Cooks',
    '6251': 'Butchers, Meat Cutters and Fishmongers - Retail and Wholesale',
    '6252': 'Bakers',
    '6261': 'Police Officers (Except Commissioned)',
    '6262': 'Firefighters',
    '6271': 'Hairstylists and Barbers',
    '6272': 'Funeral Directors and Embalmers',
    '6411': 'Sales Representatives - Wholesale Trade (Non-Technical)',
    '6421': 'Retail Salespersons and Sales Clerks',
    '6431': 'Travel Counsellors',
    '6432': 'Pursers and Flight Attendants',
    '6433': 'Airline Sales and Service Agents',
    '6434': 'Ticket Agents, Cargo Service Representatives and Related Clerks (Except Airline)',
    '6435': 'Hotel Front Desk Clerks',
    '6441': 'Tour and Travel Guides',
    '6442': 'Outdoor Sport and Recreational Guides',
    '6443': 'Casino Occupations',
    '6451': "Maîtres d'hôtel and Hosts/Hostesses",
    '6452': 'Bartenders',
    '6453': 'Food and Beverage Servers',
    '6461': 'Sheriffs and Bailiffs',
    '6462': 'Correctional Service Officers',
    '6463': 'By-Law Enforcement and Other Regulatory Officers, n.e.c.',
    '6464': 'Occupations Unique to the Armed Forces',
    '6465': 'Other Protective Service Occupations',
    '6471': 'Visiting Homemakers, Housekeepers and Related Occupations',
    '6472': 'Elementary and Secondary School Teacher Assistants',
    '6474': "Babysitters, Nannies and Parents' Helpers",
    '6481': 'Image, Social and Other Personal Consultants',
    '6482': 'Estheticians, Electrologists and Related Occupations',
    '6483': 'Pet Groomers and Animal Care Workers',
    '6484': 'Other Personal Service Occupations',
    '6611': 'Cashiers',
    '6621': 'Service Station Attendants',
    '6622': 'Grocery Clerks and Store Shelf Stockers',
    '6623': 'Other Elemental Sales Occupations',
    '6641': 'Food Counter Attendants, Kitchen Helpers and Related Occupations',
    '6651': 'Security Guards and Related Occupations',
    '6661': 'Light Duty Cleaners',
    '6662': 'Specialized Cleaners',
    '6663': 'Janitors, Caretakers and Building Superintendents',
    '6671': 'Operators and Attendants in Amusement, Recreation and Sport',
    '6672': 'Other Attendants in Accommodation and Travel',
    '6681': 'Dry Cleaning and Laundry Occupations',
    '6682': 'Ironing, Pressing and Finishing Occupations',
    '6683': 'Other Elemental Service Occupations',
    '7211': 'Supervisors, Machinists and Related Occupations',
    '7212': 'Contractors and Supervisors, Electrical Trades and Telecommunications Occupations',
    '7213': 'Contractors and Supervisors, Pipefitting Trades',
    '7214': 'Contractors and Supervisors, Metal Forming, Shaping and Erecting Trades',
    '7215': 'Contractors and Supervisors, Carpentry Trades',
    '7216': 'Contractors and Supervisors, Mechanic Trades',
    '7217': 'Contractors and Supervisors, Heavy Construction Equipment Crews',
    '7218': 'Supervisors, Printing and Related Occupations',
    '7219': 'Contractors and Supervisors, Other Construction Trades, Installers, Repairers and Servicers',
    '7221': 'Supervisors, Railway Transport Operations',
    '7222': 'Supervisors, Motor Transport and Other Ground Transit Operators',
    '7231': 'Machinists and Machining and Tooling Inspectors',
    '7232': 'Tool and Die Makers',
    '7241': 'Electricians (Except Industrial and Power System)',
    '7242': 'Industrial Electricians',
    '7243': 'Power System Electricians',
    '7244': 'Electrical Power Line and Cable Workers',
    '7245': 'Telecommunications Line and Cable Workers',
    '7246': 'Telecommunications Installation and Repair Workers',
    '7247': 'Cable Television Service and Maintenance Technicians',
    '7251': 'Plumbers',
    '7252': 'Steamfitters, Pipefitters and Sprinkler System Installers',
    '7253': 'Gas Fitters',
    '7261': 'Sheet Metal Workers',
    '7262': 'Boilermakers',
    '7263': 'Structural Metal and Platework Fabricators and Fitters',
    '7264': 'Ironworkers',
    '7265': 'Welders and Related Machine Operators',
    '7266': 'Blacksmiths and Die Setters',
    '7271': 'Carpenters',
    '7272': 'Cabinetmakers',
    '7281': 'Bricklayers',
    '7282': 'Concrete Finishers',
    '7283': 'Tilesetters',
    '7284': 'Plasterers, Drywall Installers and Finishers and Lathers',
    '7291': 'Roofers and Shinglers',
    '7292': 'Glaziers',
    '7293': 'Insulators',
    '7294': 'Painters and Decorators',
    '7295': 'Floor Covering Installers',
    '7311': 'Construction Millwrights and Industrial Mechanics (Except Textile)',
    '7312': 'Heavy-Duty Equipment Mechanics',
    '7313': 'Refrigeration and Air Conditioning Mechanics',
    '7314': 'Railway Carmen/women',
    '7315': 'Aircraft Mechanics and Aircraft Inspectors',
    '7316': 'Machine Fitters',
    '7317': 'Textile Machinery Mechanics and Repairers',
    '7318': 'Elevator Constructors and Mechanics',
    '7321': 'Automotive Service Technicians, Truck and Bus Mechanics and Mechanical Repairers',
    '7322': 'Motor Vehicle Body Repairers',
    '7331': 'Oil and Solid Fuel Heating Mechanics',
    '7332': 'Electric Appliance Servicers and Repairers',
    '7333': 'Electrical Mechanics',
    '7334': 'Motorcycle and Other Related Mechanics',
    '7335': 'Other Small Engine and Equipment Mechanics',
    '7341': 'Upholsterers',
    '7342': 'Tailors, Dressmakers, Furriers and Milliners',
    '7343': 'Shoe Repairers and Shoemakers',
    '7344': 'Jewellers, Watch Repairers and Related Occupations',
    '7351': 'Stationary Engineers and Auxiliary Equipment Operators',
    '7352': 'Power Systems and Power Station Operators',
    '7361': 'Railway and Yard Locomotive Engineers',
    '7362': 'Railway Conductors and Brakemen/women',
    '7371': 'Crane Operators',
    '7372': 'Drillers and Blasters - Surface Mining, Quarrying and Construction',
    '7373': 'Water Well Drillers',
    '7381': 'Printing Press Operators',
    '7382': 'Commercial Divers',
    '7383': 'Other Trades and Related Occupations',
    '7411': 'Truck Drivers',
    '7412': 'Bus Drivers, Subway Operators and Other Transit Operators',
    '7413': 'Taxi and Limousine Drivers and Chauffeurs',
    '7414': 'Delivery and Courier Service Drivers',
    '7421': 'Heavy Equipment Operators (Except Crane)',
    '7422': 'Public Works Maintenance Equipment Operators',
    '7431': 'Railway Yard Workers',
    '7432': 'Railway Track Maintenance Workers',
    '7433': 'Deck Crew, Water Transport',
    '7434': 'Engine Room Crew, Water Transport',
    '7435': 'Lock and Cable Ferry Operators and Related Occupations',
    '7436': 'Boat Operators',
    '7437': 'Air Transport Ramp Attendants',
    '7441': 'Residential and Commercial Installers and Servicers',
    '7442': 'Waterworks and Gas Maintenance Workers',
    '7443': 'Automotive Mechanical Installers and Servicers',
    '7444': 'Pest Controllers and Fumigators',
    '7445': 'Other Repairers and Servicers',
    '7451': 'Longshore Workers',
    '7452': 'Material Handlers',
    '7611': 'Construction Trades Helpers and Labourers',
    '7612': 'Other Trades Helpers and Labourers',
    '7621': 'Public Works and Maintenance Labourers',
    '7622': 'Railway and Motor Transport Labourers',
    '8211': 'Supervisors, Logging and Forestry',
    '8221': 'Supervisors, Mining and Quarrying',
    '8222': 'Supervisors, Oil and Gas Drilling and Service',
    '8231': 'Underground Production and Development Miners',
    '8232': 'Oil and Gas Well Drillers, Servicers, Testers and Related Workers',
    '8241': 'Logging Machinery Operators',
    '8251': 'Farmers and Farm Managers',
    '8252': 'Agricultural and Related Service Contractors and Managers',
    '8253': 'Farm Supervisors and Specialized Livestock Workers',
    '8254': 'Nursery and Greenhouse Operators and Managers',
    '8255': 'Landscaping and Grounds Maintenance Contractors and Managers',
    '8256': 'Supervisors, Landscape and Horticulture',
    '8257': 'Aquaculture Operators and Managers',
    '8261': 'Fishing Masters and Officers',
    '8262': 'Fishing Vessel Skippers and Fishermen/women',
    '8411': 'Underground Mine Service and Support Workers',
    '8412': 'Oil and Gas Well Drilling Workers and Services Operators',
    '8421': 'Chain Saw and Skidder Operators',
    '8422': 'Silviculture and Forestry Workers',
    '8431': 'General Farm Workers',
    '8432': 'Nursery and Greenhouse Workers',
    '8441': 'Fishing Vessel Deckhands',
    '8442': 'Trappers and Hunters',
    '8611': 'Harvesting Labourers',
    '8612': 'Landscaping and Grounds Maintenance Labourers',
    '8613': 'Aquaculture and Marine Harvest Labourers',
    '8614': 'Mine Labourers',
    '8615': 'Oil and Gas Drilling, Servicing and Related Labourers',
    '8616': 'Logging and Forestry Labourers',
    '9211': 'Supervisors, Mineral and Metal Processing',
    '9212': 'Supervisors, Petroleum, Gas and Chemical Processing and Utilities',
    '9213': 'Supervisors, Food, Beverage and Tobacco Processing',
    '9214': 'Supervisors, Plastic and Rubber Products Manufacturing',
    '9215': 'Supervisors, Forest Products Processing',
    '9216': 'Supervisors, Textile Processing',
    '9221': 'Supervisors, Motor Vehicle Assembling',
    '9222': 'Supervisors, Electronics Manufacturing',
    '9223': 'Supervisors, Electrical Products Manufacturing',
    '9224': 'Supervisors, Furniture and Fixtures Manufacturing',
    '9225': 'Supervisors, Fabric, Fur and Leather Products Manufacturing',
    '9226': 'Supervisors, Other Mechanical and Metal Products Manufacturing',
    '9227': 'Supervisors, Other Products Manufacturing and Assembly',
    '9231': 'Central Control and Process Operators, Mineral and Metal Processing',
    '9232': 'Petroleum, Gas and Chemical Process Operators',
    '9233': 'Pulping Control Operators',
    '9234': 'Papermaking and Coating Control Operators',
    '9411': 'Machine Operators, Mineral and Metal Processing',
    '9412': 'Foundry Workers',
    '9413': 'Glass Forming and Finishing Machine Operators and Glass Cutters',
    '9414': 'Concrete, Clay and Stone Forming Operators',
    '9415': 'Inspectors and Testers, Mineral and Metal Processing',
    '9421': 'Chemical Plant Machine Operators',
    '9422': 'Plastics Processing Machine Operators',
    '9423': 'Rubber Processing Machine Operators and Related Workers',
    '9424': 'Water and Waste Plant Operators',
    '9431': 'Sawmill Machine Operators',
    '9432': 'Pulp Mill Machine Operators',
    '9433': 'Papermaking and Finishing Machine Operators',
    '9434': 'Other Wood Processing Machine Operators',
    '9435': 'Paper Converting Machine Operators',
    '9436': 'Lumber Graders and Other Wood Processing Inspectors and Graders',
    '9441': 'Textile Fibre and Yarn Preparation Machine Operators',
    '9442': 'Weavers, Knitters and Other Fabric-Making Occupations',
    '9443': 'Textile Dyeing and Finishing Machine Operators',
    '9444': 'Textile Inspectors, Graders and Samplers',
    '9451': 'Sewing Machine Operators',
    '9452': 'Fabric, Fur and Leather Cutters',
    '9453': 'Hide and Pelt Processing Workers',
    '9454': 'Inspectors and Testers, Fabric, Fur and Leather Products Manufacturing',
    '9461': 'Process Control and Machine Operators, Food and Beverage Processing',
    '9462': 'Industrial Butchers and Meat Cutters, Poultry Preparers and Related Workers',
    '9463': 'Fish Plant Workers',
    '9464': 'Tobacco Processing Machine Operators',
    '9465': 'Testers and Graders, Food and Beverage Processing',
    '9471': 'Printing Machine Operators',
    '9472': 'Camera, Platemaking and Other Prepress Occupations',
    '9473': 'Binding and Finishing Machine Operators',
    '9474': 'Photographic and Film Processors',
    '9481': 'Aircraft Assemblers and Aircraft Assembly Inspectors',
    '9482': 'Motor Vehicle Assemblers, Inspectors and Testers',
    '9483': 'Electronics Assemblers, Fabricators, Inspectors and Testers',
    '9484': 'Assemblers and Inspectors, Electrical Appliance, Apparatus and Equipment Manufacturing',
    '9485': 'Assemblers, Fabricators and Inspectors, Industrial Electrical Motors and Transformers',
    '9486': 'Mechanical Assemblers and Inspectors',
    '9487': 'Machine Operators and Inspectors, Electrical Apparatus Manufacturing',
    '9491': 'Boat Assemblers and Inspectors',
    '9492': 'Furniture and Fixture Assemblers and Inspectors',
    '9493': 'Other Wood Products Assemblers and Inspectors',
    '9494': 'Furniture Finishers and Refinishers',
    '9495': 'Plastic Products Assemblers, Finishers and Inspectors',
    '9496': 'Painters and Coaters - Industrial',
    '9497': 'Plating, Metal Spraying and Related Operators',
    '9498': 'Other Assemblers and Inspectors',
    '9511': 'Machining Tool Operators',
    '9512': 'Forging Machine Operators',
    '9513': 'Woodworking Machine Operators',
    '9514': 'Metalworking Machine Operators',
    '9516': 'Other Metal Products Machine Operators',
    '9517': 'Other Products Machine Operators',
    '9611': 'Labourers in Mineral and Metal Processing',
    '9612': 'Labourers in Metal Fabrication',
    '9613': 'Labourers in Chemical Products Processing and Utilities',
    '9614': 'Labourers in Wood, Pulp and Paper Processing',
    '9615': 'Labourers in Rubber and Plastic Products Manufacturing',
    '9616': 'Labourers in Textile Processing',
    '9617': 'Labourers in Food, Beverage and Tobacco Processing',
    '9618': 'Labourers in Fish Processing',
    '9619': 'Other Labourers in Processing, Manufacturing and Utilities'}

